[project]
authors = ["darrenkjr <darren.rajit1@monash.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "livingebg-screen-simstudy"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
pandas = ">=2.2.3,<3"
pyarrow = ">=19.0.0,<20"
colorlog = ">=6.9.0,<7"
transformers = ">=4.49.0,<5"

[pypi-dependencies]
asreview = ">=1.6.5, <2"
buscarpy = ">=0.0.2, <0.0.3"
transformers = ">=4.47.1, <5"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]

[feature.gpu.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu124" }

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cpu" }

