[project]
authors = ["darrenkjr <darren.rajit1@monash.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "livingebg-screen-simstudy"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.0,<3.13"
pandas = ">=2.2.3,<3"
pyarrow = ">=19.0.0,<20"
colorlog = ">=6.9.0,<7"
seaborn = ">=0.13.2,<0.14"
transformers = "==4.47.1"
kiwisolver = ">=1.4.7,<2"
matplotlib = ">=3.10.1,<4"
gensim = ">=4.3.2,<5"
scipy = "<1.13"

[pypi-dependencies]
asreview = ">=1.6.5, <2"
buscarpy = ">=0.0.2, <0.0.3"
adapters = ">=1.1.0, <2"
sentence-transformers = ">=3.4.1, <4"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]

[feature.gpu.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu126"}
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu126"}

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cpu" }

