[project]
authors = ["darrenkjr <darren.rajit1@monash.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "livingebg-screen-simstudy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
pandas = ">=2.2.3,<3"

[pypi-dependencies]
asreview = ">=1.6.5, <2"
buscarpy = ">=0.0.2, <0.0.3"
